export const SHORT_CUTS= [
    {key: 'F9', des: '切换实时预览', desEn: 'Switch watch/unwatch'},
    {key: 'F10', des: '全屏HTML预览(按 ESC 退出)', desEn: 'Full preview HTML (Press ESC exit)'},
    {key: 'F11', des: '切换全屏状态(按 F11 退出)', desEn: 'Switch fullscreen (Press F11 exit)'},
    {key: 'Ctrl + A / Command + A', des: '全选', desEn: 'Select all'},
    {key: 'Ctrl + S / Command + S', des: '保存草稿', desEn: 'Save drafts'},
    {key: 'Ctrl + Z / Command + Z', des: '撤销', desEn: 'Undo'},
    {key: 'Ctrl + Shift + Z / Command + Shift + Z', des: '重做(快捷一)', desEn: 'Redo'},
    {key: 'Ctrl + Y / Command + Y', des: '重做(快捷二)', desEn: 'Redo'},
    {key: 'Ctrl + V / Command + V', des: '粘贴', desEn: 'Paste'},
    {key: 'Ctrl + 1~6 / Command + 1~6', des: '插入标题1~6', desEn: 'Insert heading 1~6'},
    {key: 'Ctrl + B / Command + B', des: '插入粗体', desEn: 'Insert bold'},
    {key: 'Ctrl + I / Command + I', des: '插入斜体', desEn: 'Insert italic'},
    {key: 'Ctrl + Shift + S / Command + Shift + S', des: '插入删除线', desEn: 'Insert strikethrough'},
    {key: 'Ctrl + Shift + U / Command + Shift + U', des: '插入下划线', desEn: 'Insert underline'},
    {key: 'Ctrl + H / Command + H', des: '插入分割线', desEn: 'Insert cut-off rule'},
    {key: 'Ctrl + Shift + C / Command + Shift + C', des: '行内代码', desEn: 'Inline Code'},
    {key: 'Ctrl + H / Command + K', des: '代码块', desEn: 'Code block'},
    {key: 'Ctrl + U / Command + U', des: '插入无序列表', desEn: 'Insert unordered list'},
    {key: 'Ctrl + Shift + O / Command + Shift + O', des: '插入有序列表', desEn: 'Insert ordered list'},
    {key: 'Ctrl + Q / Command + Q', des: '插入引用', desEn: 'Insert blockquotes'},
    {key: 'Ctrl + L / Command + L', des: '插入链接', desEn: 'Insert link'},
    {key: 'Ctrl + G / Command + G', des: '插入图片', desEn: 'Insert picture'},
    {key: '/', des: '更多(空白行输入 " / " 弹出快捷菜单)', desEn: 'More'},
]
