export const SHORT_CUTS= [
    {key: 'F9', des: '切换实时预览', desEn: 'Switch watch/unwatch'},
    {key: 'F10', des: '全屏HTML预览(按 ESC 退出)', desEn: 'Full preview HTML (Press ESC exit)'},
    {key: 'F11', des: '切换全屏状态(按 F11 退出)', desEn: 'Switch fullscreen (Press F11 exit)'},
    {key: 'Ctrl + S / Command + S', des: '保存草稿', desEn: 'Save drafts'},
    {key: 'Ctrl + Z / Command + Z', des: '撤销', desEn: 'Undo'},
    {key: 'Ctrl + Shift + Z / Command + Shift + Z', des: '重做(快捷一)', desEn: 'Redo'},
    {key: 'Ctrl + Y / Command + Y', des: '重做(快捷二)', desEn: 'Redo'},
    {key: 'Ctrl + V / Command + V', des: '粘贴', desEn: 'Paste'},
    {key: 'Ctrl + B / Command + B', des: '插入粗体', desEn: 'Insert bold'},
    {key: 'Ctrl + I / Command + I', des: '插入斜体', desEn: 'Insert italic'},
    {key: 'Ctrl + L / Command + L', des: '插入链接', desEn: 'Insert link'},
    {key: 'Ctrl + G / Command + G', des: '插入图片', desEn: 'Insert picture'},
    {key: '/', des: '更多(空白行输入 " / " 弹出快捷菜单)', desEn: 'More'},
    /*{key: 'Ctrl + 1~6 / Command + 1~6', des: '插入标题1~6', desEn: 'Insert heading 1~6'},
    {key: 'Ctrl + A / Command + A', des: '全选', desEn: 'Select all'},
    {key: 'Ctrl + D / Command + D', des: '插入日期时间', desEn: 'Insert datetime'},
    {key: 'Ctrl + E / Command + E', des: '插入Emoji符号', desEn: 'Insert :emoji:'},
    {key: 'Ctrl + F / Command + F', des: '查找/搜索', desEn: 'Start searching'},
    {key: 'Ctrl + H / Command + H', des: '插入水平线', desEn: 'Insert horizontal rule'},
    {key: 'Ctrl + K / Command + K', des: '插入行内代码', desEn: 'Insert inline code'},
    {key: 'Ctrl + U / Command + U', des: '插入无序列表', desEn: 'Insert unordered list'},
    {key: 'Ctrl + Q', des: '代码折叠切换', desEn: 'Switch code fold'},
    {key: 'Ctrl + Shift + A', des: '插入@链接', desEn: 'Insert @link'},
    {key: 'Ctrl + Shift + C', des: '插入行内代码', desEn: 'Insert inline code'},
    {key: 'Ctrl + Shift + E', des: '打开插入Emoji表情对话框', desEn: 'Open emoji dialog'},
    {key: 'Ctrl + Shift + F / Shift+ Command + F', des: '替换', desEn: 'Replace'},
    {key: 'Ctrl + Shift + G / Shift+ Command + G', des: '切换到上一个搜索结果项', desEn: 'Find previous search results'},
    {key: 'Ctrl + Shift + H', des: '打开HTML实体字符对话框', desEn: 'Open HTML Entities dialog'},
    {key: 'Ctrl + Shift + I', des: '插入图片', desEn: 'Insert image ![]()'},
    {key: 'Ctrl + Shift + K', des: '插入TeX(KaTeX)公式符号', desEn: 'Insert TeX(KaTeX) symbol $$TeX$$'},
    {key: 'Ctrl + Shift + L', des: '打开插入链接对话框', desEn: 'Open link dialog'},
    {key: 'Ctrl + Shift + O', des: '插入有序列表', desEn: 'Insert ordered list'},
    {key: 'Ctrl + Shift + P', des: '打开插入PRE对话框', desEn: 'Open Preformatted text dialog'},
    {key: 'Ctrl + Shift + Q', des: '插入引用', desEn: 'Insert blockquotes'},
    {key: 'Ctrl + Shift + R / Shift+ Command + Option + F', des: '全部替换', desEn: 'Replace all'},
    {key: 'Ctrl + Shift + S', des: '插入删除线', desEn: 'Insert strikethrough'},
    {key: 'Ctrl + Shift + T', des: '打开插入表格对话框', desEn: 'Open table dialog'},
    {key: 'Ctrl + Shift + U', des: '将所选文字转成大写', desEn: 'Selection text convert to uppercase'},
    {key: 'Shift + Alt + C', des: '插入```代码', desEn: 'Insert code blocks (```)'},
    {key: 'Shift + Alt + H', des: '打开使用帮助对话框', desEn: 'Open help dialog'},
    {key: 'Shift + Alt + L', des: '打开使用帮助对话框', desEn: 'Open help dialog'},
    {key: 'Shift + Alt + P', des: '插入分页符', desEn: 'Insert page break'},
    {key: 'Alt + L', des: '将所选文本转成小写', desEn: 'Selection text convert to lowercase'},
    {key: 'Shift + Alt + U', des: '将所选的每个单词的首字母转成大写', desEn: 'Selection words first letter convert to Uppercase'},
    {key: 'Ctrl + Shift + Alt + C', des: '打开插入代码块对话框层', desEn: 'Open code blocks dialog'},
    {key: 'Ctrl + Shift + Alt + I', des: '打开插入图片对话框层', desEn: 'Open image dialog'},
    {key: 'Ctrl + Shift + Alt + U', des: '将所选文本的第一个首字母转成大写', desEn: 'Selection text first letter convert to uppercase'},
    {key: 'Ctrl + Alt + G', des: '跳转到指定的行', desEn: 'Goto line'},*/
]
